# Generated by Django 4.1.5 on 2023-01-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='create_date',
        ),
    ]
